In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')
data.head()

   ID_Patient_Care_Situation  ...  Survived_1_year
0                      22374  ...                0
1                      18164  ...                1
2                       6283  ...                0
3                       5339  ...                1
4                      33012  ...                1

[5 rows x 18 columns]

In [3]:
data=data.drop(['ID_Patient_Care_Situation','Patient_ID','Patient_mental_condition','Number_of_prev_cond'],axis=1)
data.head()

   Diagnosed_Condition Treated_with_drugs  ...    Z  Survived_1_year
0                    8                DX6  ...  0.0                0
1                    5               DX2   ...  0.0                1
2                   23                DX6  ...  0.0                0
3                   51               DX1   ...  0.0                1
4                    0                NaN  ...  1.0                1

[5 rows x 14 columns]

In [4]:
data = data[data['Treated_with_drugs'].notna()]
data.reset_index(inplace = True,drop=True)
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23084 entries, 0 to 23083
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Diagnosed_Condition      23084 non-null  int64
 1   Treated_with_drugs       23084 non-null  object
 2   Patient_Age              23084 non-null  int64
 3   Patient_Body_Mass_Index  23084 non-null  float64
 4   Patient_Smoker           23084 non-null  object
 5   Patient_Rural_Urban      23084 non-null  object
 6   A                        21849 non-null  float64
 7   B                        21849 non-null  float64
 8   C                        21849 non-null  float64
 9   D                        21849 non-null  float64
 10  E                        21849 non-null  float64
 11  F                        21849 non-null  float64
 12  Z                        21849 non-null  float64
 13  Survived_1_year          23084 non-null  int64
dtypes: float64(8), int64(3), object(3)
memory usage: 2.5+ MB

   Diagnosed_Condition Treated_with_drugs  ...    Z  Survived_1_year
0                    8                DX6  ...  0.0                0
1                    5               DX2   ...  0.0                1
2                   23                DX6  ...  0.0                0
3                   51               DX1   ...  0.0                1
4                   45                DX6  ...  0.0                0

[5 rows x 14 columns]

In [5]:
data['Patient_Smoker'].describe()
print(sum(data['Patient_Smoker']=="YES"))
print(sum(data['Patient_Smoker']=="NO"))
print(sum(data['Patient_Smoker']=="Cannot say"))
data = pd.get_dummies(data, columns=['Patient_Smoker', 'Patient_Rural_Urban'])
data.head()

9838
13246
0

   Diagnosed_Condition  ... Patient_Rural_Urban_URBAN
0                    8  ...                         1
1                    5  ...                         0
2                   23  ...                         0
3                   51  ...                         1
4                   45  ...                         1

[5 rows x 16 columns]

In [6]:
data['DX1']=0
data['DX2']=0
data['DX3']=0
data['DX4']=0
data['DX5']=0
data['DX6']=0
for i in range(0,23084):
  if data.loc[i,'Treated_with_drugs']=='DX6':
    data.loc[i,'DX6'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 ':
    data.loc[i,'DX2'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 ':
    data.loc[i,'DX1'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX3 ':
    data.loc[i,'DX3'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX5 ':
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX4 ':
    data.loc[i,'DX4'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX5 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX3 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX3 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX3'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX2'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX3 DX4 ':
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX4 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX4'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX4 DX5 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX3 DX5 ':
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX4 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX4'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX3 DX4 DX5 ':
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX3 DX5 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX4 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX1'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX4 DX5 ':
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX3 DX4 ':
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX2'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX4 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX4 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX2'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX3 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX3 DX4 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX3 DX4 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX4 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX2 DX3 DX4 DX5 ':
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX2'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX5'] = 1
  elif data.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX4 DX5 ':
    data.loc[i,'DX1'] = 1
    data.loc[i,'DX3'] = 1
    data.loc[i,'DX4'] = 1
    data.loc[i,'DX5'] = 1
    data.loc[i,'DX2'] = 1

In [7]:
data=data.dropna()
data.isnull().sum()

Diagnosed_Condition          0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Survived_1_year              0
Patient_Smoker_NO            0
Patient_Smoker_YES           0
Patient_Rural_Urban_RURAL    0
Patient_Rural_Urban_URBAN    0
DX1                          0
DX2                          0
DX3                          0
DX4                          0
DX5                          0
DX6                          0
dtype: int64

In [8]:
X=data.drop(columns=['Treated_with_drugs','Survived_1_year'],axis=1)
Y=data['Survived_1_year']
X.head()

   Diagnosed_Condition  Patient_Age  Patient_Body_Mass_Index  ...  DX4  DX5  DX6
0                    8           56                18.479385  ...    0    0    1
1                    5           36                22.945566  ...    0    0    0
2                   23           48                27.510027  ...    0    0    1
3                   51            5                19.130976  ...    0    0    0
4                   45           47                26.155120  ...    0    0    1

[5 rows x 20 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=1)

In [10]:
test_new = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [11]:
test_new=test_new.drop(['ID_Patient_Care_Situation','Patient_ID','Patient_mental_condition'],axis=1)
test_new.head()

   Diagnosed_Condition Treated_with_drugs  ...    Z  Number_of_prev_cond
0                   40               DX3   ...  0.0                  2.0
1                   52                DX6  ...  0.0                  2.0
2                   50           DX4 DX5   ...  0.0                  2.0
3                   32                DX6  ...  0.0                  3.0
4                   20               DX3   ...  0.0                  1.0

[5 rows x 14 columns]

In [12]:
test_new = test_new[test_new['Treated_with_drugs'].notna()]
test_new.reset_index(inplace = True,drop=True)
test_new.info()
test_new.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9303 entries, 0 to 9302
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Diagnosed_Condition      9303 non-null   int64
 1   Treated_with_drugs       9303 non-null   object
 2   Patient_Age              9303 non-null   int64
 3   Patient_Body_Mass_Index  9303 non-null   float64
 4   Patient_Smoker           9303 non-null   object
 5   Patient_Rural_Urban      9303 non-null   object
 6   A                        9303 non-null   float64
 7   B                        9303 non-null   float64
 8   C                        9303 non-null   float64
 9   D                        9303 non-null   float64
 10  E                        9303 non-null   float64
 11  F                        9303 non-null   float64
 12  Z                        9303 non-null   float64
 13  Number_of_prev_cond      9303 non-null   float64
dtypes: float64(9), int64(2), object(3)
memory usage: 1017.6+ KB

   Diagnosed_Condition Treated_with_drugs  ...    Z  Number_of_prev_cond
0                   40               DX3   ...  0.0                  2.0
1                   52                DX6  ...  0.0                  2.0
2                   50           DX4 DX5   ...  0.0                  2.0
3                   32                DX6  ...  0.0                  3.0
4                   20               DX3   ...  0.0                  1.0

[5 rows x 14 columns]

In [13]:
test_new['Patient_Smoker'].describe()
print(sum(test_new['Patient_Smoker']=="YES"))
print(sum(test_new['Patient_Smoker']=="NO"))
print(sum(test_new['Patient_Smoker']=="Cannot say"))
test_new = pd.get_dummies(test_new, columns=['Patient_Smoker', 'Patient_Rural_Urban'])
test_new.head()

3970
5333
0

   Diagnosed_Condition  ... Patient_Rural_Urban_URBAN
0                   40  ...                         0
1                   52  ...                         1
2                   50  ...                         0
3                   32  ...                         1
4                   20  ...                         0

[5 rows x 16 columns]

In [14]:
test_new['DX1']=0
test_new['DX2']=0
test_new['DX3']=0
test_new['DX4']=0
test_new['DX5']=0
test_new['DX6']=0
size=test_new.shape[0]
for i in range(0,size):
  if test_new.loc[i,'Treated_with_drugs']=='DX6':
    test_new.loc[i,'DX6'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 ':
    test_new.loc[i,'DX2'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 ':
    test_new.loc[i,'DX1'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX3 ':
    test_new.loc[i,'DX3'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX5 ':
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX4 ':
    test_new.loc[i,'DX4'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX5 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX3 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX3 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX3'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX2'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX3 DX4 ':
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX4 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX4'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX4 DX5 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX3 DX5 ':
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX4 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX4'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX3 DX4 DX5 ':
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX3 DX5 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX4 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX1'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX4 DX5 ':
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX3 DX4 ':
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX2'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX4 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX4 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX2'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX3 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX3 DX4 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX3 DX4 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX4 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX2 DX3 DX4 DX5 ':
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX2'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX5'] = 1
  elif test_new.loc[i,'Treated_with_drugs']=='DX1 DX2 DX3 DX4 DX5 ':
    test_new.loc[i,'DX1'] = 1
    test_new.loc[i,'DX3'] = 1
    test_new.loc[i,'DX4'] = 1
    test_new.loc[i,'DX5'] = 1
    test_new.loc[i,'DX2'] = 1

In [15]:
test_new=test_new.dropna()
test_new.isnull().sum()

Diagnosed_Condition          0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
Patient_Smoker_NO            0
Patient_Smoker_YES           0
Patient_Rural_Urban_RURAL    0
Patient_Rural_Urban_URBAN    0
DX1                          0
DX2                          0
DX3                          0
DX4                          0
DX5                          0
DX6                          0
dtype: int64

In [16]:
test_new=test_new.drop(['Treated_with_drugs','Number_of_prev_cond'],axis=1)
test_new.head()

   Diagnosed_Condition  Patient_Age  Patient_Body_Mass_Index  ...  DX4  DX5  DX6
0                   40           16                29.443894  ...    0    0    0
1                   52           24                26.836321  ...    0    0    1
2                   50           63                25.523280  ...    1    1    0
3                   32           42                27.171155  ...    0    0    1
4                   20           50                25.556192  ...    0    0    0

[5 rows x 20 columns]

In [17]:
!pip install catboost
!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/b2/aa/e61819d04ef2bbee778bf4b3a748db1f3ad23512377e43ecfdc3211437a0/catboost-0.23.2-cp36-none-manylinux1_x86_64.whl (64.8MB)
     |████████████████████████████████| 64.8MB 61kB/s
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost) (1.12.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.0.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.18.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.23.2
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.6/dist-packages (7.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.6/dist-packages (from ipywidgets) (4.10.1)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.6/dist-packages (from ipywidgets) (4.3.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets) (5.0.7)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /usr/local/lib/python3.6/dist-packages (from ipywidgets) (5.5.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets) (5.3.4)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets) (4.5.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.3.1->ipywidgets) (1.12.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.3.1->ipywidgets) (4.4.2)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.3.1->ipywidgets) (0.2.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.6/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets) (5.2.2)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets) (4.6.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets) (2.6.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (2.1.3)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.8.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (1.0.18)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (47.3.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (4.8.0)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.6/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (19.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets) (2.8.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (5.6.1)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.8.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (2.11.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.6.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.4.4)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.3)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (3.1.5)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (1.1.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (0.5.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (20.4)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets) (2.4.7)
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

In [18]:
import catboost 
from catboost import CatBoostClassifier, Pool, cv
from sklearn.metrics import f1_score

In [19]:
model = CatBoostClassifier(
    random_seed=18,logging_level='Silent',
    iterations=1000,learning_rate=0.015,depth=6,
   l2_leaf_reg=5,loss_function='Logloss',
   leaf_estimation_iterations=10
)
model.fit(x_train,y_train);
y_pred = model.predict(x_test)

In [20]:
f1_score(y_test,y_pred)

0.8718241507279474

In [21]:
model = CatBoostClassifier(
    random_seed=18,logging_level='Silent',
    iterations=1000,learning_rate=0.015,depth=6,
   l2_leaf_reg=5,loss_function='Logloss',
   leaf_estimation_iterations=10,
)
model.fit(X,Y);
y_pred = model.predict(test_new)

In [22]:
from google.colab import drive
drive.mount('drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at drive

In [23]:
pre=pd.DataFrame(y_pred)
pre.to_csv('data.csv')
!cp data.csv "drive/My Drive/"