In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')
data

       ID_Patient_Care_Situation  ...  Survived_1_year
0                          22374  ...                0
1                          18164  ...                1
2                           6283  ...                0
3                           5339  ...                1
4                          33012  ...                1
...                          ...  ...              ...
23092                      15613  ...                0
23093                      15503  ...                1
23094                       2167  ...                0
23095                      31646  ...                1
23096                       3947  ...                0

[23097 rows x 18 columns]

In [3]:
data.Patient_mental_condition.value_counts()

Stable    23097
Name: Patient_mental_condition, dtype: int64

In [4]:
data=data.drop('Patient_mental_condition',axis=1)

In [5]:
data.Z.value_counts()

0.0    21849
1.0       13
Name: Z, dtype: int64

In [7]:
data=data.drop('Z',axis=1)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23084 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   A                          21862 non-null  float64
 9   B                          21862 non-null  float64
 10  C                          21862 non-null  float64
 11  D                          21862 non-null  float64
 12  E                          21862 non-null  float64
 13  F                          21862 non-null  float64
 14  Number_of_prev_cond        21862 non-null  float64
 15  Survived_1_year            23097 non-null  int64
dtypes: float64(8), int64(5), object(3)
memory usage: 2.8+ MB

In [9]:
from scipy import stats
cols=['Treated_with_drugs','A','B','C','D','E','F']
for i in cols:
      data[i]=data[i].fillna(stats.mode(data[i])[0][0])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23097 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   A                          23097 non-null  float64
 9   B                          23097 non-null  float64
 10  C                          23097 non-null  float64
 11  D                          23097 non-null  float64
 12  E                          23097 non-null  float64
 13  F                          23097 non-null  float64
 14  Number_of_prev_cond        21862 non-null  float64
 15  Survived_1_year            23097 non-null  int64
dtypes: float64(8), int64(5), object(3)
memory usage: 2.8+ MB

In [11]:
for i in range(23097):  
    data.Number_of_prev_cond[i]=data.A[i]+data.B[i]+data.C[i]+data.D[i]+data.E[i]+data.F[i]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23097 entries, 0 to 23096
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID_Patient_Care_Situation  23097 non-null  int64
 1   Diagnosed_Condition        23097 non-null  int64
 2   Patient_ID                 23097 non-null  int64
 3   Treated_with_drugs         23097 non-null  object
 4   Patient_Age                23097 non-null  int64
 5   Patient_Body_Mass_Index    23097 non-null  float64
 6   Patient_Smoker             23097 non-null  object
 7   Patient_Rural_Urban        23097 non-null  object
 8   A                          23097 non-null  float64
 9   B                          23097 non-null  float64
 10  C                          23097 non-null  float64
 11  D                          23097 non-null  float64
 12  E                          23097 non-null  float64
 13  F                          23097 non-null  float64
 14  Number_of_prev_cond        23097 non-null  float64
 15  Survived_1_year            23097 non-null  int64
dtypes: float64(8), int64(5), object(3)
memory usage: 2.8+ MB

In [13]:
for i in range(23097):
  if data.Patient_Smoker[i]=='Cannot say':
    data.Patient_Smoker[i]='NO'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
data

       ID_Patient_Care_Situation  ...  Survived_1_year
0                          22374  ...                0
1                          18164  ...                1
2                           6283  ...                0
3                           5339  ...                1
4                          33012  ...                1
...                          ...  ...              ...
23092                      15613  ...                0
23093                      15503  ...                1
23094                       2167  ...                0
23095                      31646  ...                1
23096                       3947  ...                0

[23097 rows x 16 columns]

In [15]:
data=pd.get_dummies(data,columns=['Treated_with_drugs','Patient_Smoker','Patient_Rural_Urban'])

In [16]:
data

       ID_Patient_Care_Situation  ...  Patient_Rural_Urban_URBAN
0                          22374  ...                          1
1                          18164  ...                          0
2                           6283  ...                          0
3                           5339  ...                          1
4                          33012  ...                          0
...                          ...  ...                        ...
23092                      15613  ...                          0
23093                      15503  ...                          0
23094                       2167  ...                          0
23095                      31646  ...                          0
23096                       3947  ...                          0

[23097 rows x 49 columns]

In [17]:
X=data.drop('Survived_1_year',axis=1)
y=data[['Survived_1_year']]

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=9,test_size=0.2)

In [19]:
test_new=pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')
test_new=test_new.drop(['Patient_mental_condition','Z'],axis=1)
test_new=pd.get_dummies(test_new,columns=['Treated_with_drugs','Patient_Smoker','Patient_Rural_Urban'])

In [20]:
test_new

      ID_Patient_Care_Situation  ...  Patient_Rural_Urban_URBAN
0                         19150  ...                          0
1                         23216  ...                          1
2                         11890  ...                          0
3                          7149  ...                          1
4                         22845  ...                          0
...                         ...  ...                        ...
9298                      18245  ...                          0
9299                      15598  ...                          1
9300                      11885  ...                          1
9301                      25101  ...                          1
9302                      18855  ...                          0

[9303 rows x 48 columns]

In [21]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,f1_score
model=XGBClassifier(random_state=9,max_depth=4,gamma=0.7,subsample=1,colsample_bytree =1,scale_pos_weight =1,learning_rate=0.2,n_estimators=100).fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(f1_score(y_test,y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8432900432900433
0.8784827123195702

In [22]:
prediction=model.predict(test_new)
res = pd.DataFrame(prediction)
res.index = test_new.index # its important for comparison
res.columns = ["prediction"]

# To download the csv file locally
from google.colab import files
res.to_csv('prediction_results_HP.csv')         
files.download('prediction_results_HP.csv')